# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Место учёбы')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('podrob', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
