# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170315_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='number_news',
        ),
    ]
