# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_news_number_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
