# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20170320_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news',
            new_name='type_news',
        ),
    ]
