# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_news_number_news'),
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_news',
            name='number_news',
        ),
        migrations.AddField(
            model_name='full_news',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.News', verbose_name='новость'),
            preserve_default=False,
        ),
    ]
