# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20170316_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='full_news',
            old_name='news_id',
            new_name='news',
        ),
    ]
