# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_auto_20170316_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_news',
            name='desc_all1',
        ),
        migrations.AddField(
            model_name='full_news',
            name='desc_all_1',
            field=models.TextField(default=1, verbose_name='Часть 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='full_news',
            name='desc_all_2',
            field=models.TextField(blank=True, verbose_name='Часть 2'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='desc_all_3',
            field=models.TextField(blank=True, verbose_name='Часть 3'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='desc_all_4',
            field=models.TextField(blank=True, verbose_name='Часть 4'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='desc_all_5',
            field=models.TextField(blank=True, verbose_name='Часть 5'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='img_1',
            field=models.ImageField(blank=True, upload_to='img_1'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='img_2'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='img_3'),
        ),
        migrations.AddField(
            model_name='full_news',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='img_4'),
        ),
    ]
