# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_auto_20170317_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_news',
            name='img_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='full_news',
            name='img_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='full_news',
            name='img_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='full_news',
            name='img_4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
